### PR TITLE
Fix #649 improve graph zoom-to-fit padding calculation

### LINKED ISSUE #649: Zoom doesn't work in small screen

### PR DESCRIPTION
**Pull request by Anchel123**

### CODE REVIEW

File: app/graph/GraphView.tsx [hunk 1]
```diff
@@ -209,7 +209,14 @@ function GraphView({ graph, selectedElement, setSelectedElement, runQuery, histo
 
     const handleRunQuery = async (q: string) => {
         await runQuery(q)
-        chartRef.current?.zoomToFit(1000, 40)
+        // Get canvas dimensions
```
Comment (barakb) [inline app/graph/GraphView.tsx:212]: Can you move that to a function and call this function from here and handleCenterClick ?

**Review by barakb — CHANGES_REQUESTED** [review]

**Review by gkorland — APPROVED** [review]
